# Site settings
title: HAB.education
subtitle: "HAB.education"
email: contact@hab.education
github_username: habeducation
twitter_username: BalloonEDU
facebook_username: habgroup
owner: HAB.education
description: > 
  HAB.education - materials and blog!
baseurl: "/"
url: "http://hab.education" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.jpg"

# Build settings
markdown: kramdown

# Disqus comments
disqus_shortname: habeducation
