#!/bin/bash

echo "Now compacting CSS and generating your header template... Wait!"

# wget --post-data="input=`cat css/master.css`" --output-document=css/temp_compacted_master.css https://cssminifier.com/raw
curl -X POST -s --data-urlencode 'input@css/master.css' https://cssminifier.com/raw > css/temp_compacted_master.css

BEGIN_GEN=$(cat _includes/head_template.html | grep -n '### BEGIN INCLUDED CSS' | sed 's/\(.*\):.*/\1/g')
END_GEN=$(cat _includes/head_template.html | grep -n '### END INCLUDED CSS' | sed 's/\(.*\):.*/\1/g')
cat <(head -n $(expr $BEGIN_GEN - 1) _includes/head_template.html) css/temp_compacted_master.css <(tail -n +$(expr $END_GEN + 1) _includes/head_template.html) > _includes/head.html

rm css/temp_compacted_master.css

echo '<!-- Please do not edit this file directly, edit head_template.html and master.css, then generate it using generate_header.sh -->' | cat - _includes/head.html > temp && mv temp _includes/head.html

echo "Done!"